[package]
name = "dlib-test"
version = "0.1.0"
authors = ["Elinor Berger <elinor@safaradeg.net>"]
edition = "2021"
publish = false
rust-version = "1.56"

[dependencies]
dlib = { path = "../" }
lazy_static = { version = "1.0", optional = true }

[features]
default = ["sin"]
sin = []
nonexistant = []
dlopen = ["lazy_static"]
